# Generated by Django 5.2 on 2025-04-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_filename', models.CharField(max_length=255, unique=True)),
                ('stored_key_part', models.TextField()),
                ('location1', models.CharField(max_length=512)),
                ('location2', models.CharField(max_length=512)),
                ('location3', models.CharField(max_length=512)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
